// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.Clase;

namespace project.Migrations
{
    [DbContext(typeof(PlatiAppContext))]
    partial class PlatiAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15");

            modelBuilder.Entity("project.Clase.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CVV")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataExpirare")
                        .HasColumnType("TEXT");

                    b.Property<string>("NrCard")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carduri");
                });

            modelBuilder.Entity("project.Clase.Plata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalii")
                        .HasColumnType("TEXT");

                    b.Property<double>("Suma")
                        .HasColumnType("REAL");

                    b.Property<int>("TaxaImpozit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipPersoana")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Plata");
                });

            modelBuilder.Entity("project.Clase.Sesizare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalii")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumePersoana")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataSesizare")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sesizari");
                });

            modelBuilder.Entity("project.Clase.Plata", b =>
                {
                    b.HasOne("project.Clase.Card", null)
                        .WithMany("plati")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
